# Generated by Django 4.2 on 2023-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_unreadmessage_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebasetoken",
            field=models.CharField(
                default="O", max_length=255, verbose_name="firebasetoken"
            ),
        ),
    ]
