# Generated by Django 4.2 on 2023-05-16 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
    ]
