# Generated by Django 4.2.2 on 2023-06-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="key",
            field=models.CharField(default="somewhere", max_length=200),
            preserve_default=False,
        ),
    ]
