# Generated by Django 4.2 on 2023-05-19 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_project_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deposit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "referral_bonus",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
