# Generated by Django 4.2.2 on 2023-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_otp_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="delivery_date",
            field=models.DateField(),
        ),
    ]
